#server:
#  port: 8081

spring:
  application:
    name: department-service

  config:
    import: "optional:configserver:http://localhost:8088"
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
# Moved to config server

